# Generated by Django 5.1.5 on 2025-03-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_cor_alter_itemestoque_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
