# Generated by Django 5.1.5 on 2025-03-06 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_categoria_slug_tipo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.categoria'),
        ),
    ]
