# Generated by Django 5.1.5 on 2025-04-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_tipo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
